// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARYU3URykX5Ea9c3XcXkypAaiBoNWw9Zk',
    appId: '1:602709803018:web:e2109afd3f5da6a8b51ff3',
    messagingSenderId: '602709803018',
    projectId: 'assignment-4-17dce',
    authDomain: 'assignment-4-17dce.firebaseapp.com',
    storageBucket: 'assignment-4-17dce.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9v5TcxEpbktiqWY0HdxqksOqZlDepq-w',
    appId: '1:602709803018:android:995864d48b2e3169b51ff3',
    messagingSenderId: '602709803018',
    projectId: 'assignment-4-17dce',
    storageBucket: 'assignment-4-17dce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5YiDHctBDzHYicZ0YQ4-O-Tt9OgMqiB8',
    appId: '1:602709803018:ios:0ed8cb4809d57548b51ff3',
    messagingSenderId: '602709803018',
    projectId: 'assignment-4-17dce',
    storageBucket: 'assignment-4-17dce.appspot.com',
    iosClientId: '602709803018-bditvocl689ht0pm4oq8jqqstrd1mjtb.apps.googleusercontent.com',
    iosBundleId: 'com.example.ibaCourse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5YiDHctBDzHYicZ0YQ4-O-Tt9OgMqiB8',
    appId: '1:602709803018:ios:0ed8cb4809d57548b51ff3',
    messagingSenderId: '602709803018',
    projectId: 'assignment-4-17dce',
    storageBucket: 'assignment-4-17dce.appspot.com',
    iosClientId: '602709803018-bditvocl689ht0pm4oq8jqqstrd1mjtb.apps.googleusercontent.com',
    iosBundleId: 'com.example.ibaCourse',
  );
}
